version: "3"
services:
  rdbms:
    container_name: rdbms
    image: mariadb:10
    restart: always
    ports:
      - 3307:3306
    volumes:
      - rdbms:/var/lib/mysql
      - ./docker/rdbms/initdb:/docker-entrypoint-initdb.d
    env_file:
      - ./api/.env
    environment:
      - MYSQL_ROOT_PASSWORD=${RDBMS_ROOT_PASSWORD}
      - MYSQL_DATABASE=${RDBMS_DATABASE}
  api:
    container_name: api
    build:
      dockerfile: Dockerfile
      context: ./api
    depends_on:
      - rdbms
    volumes:
      - .:/app
      - /app/api/node_modules
    env_file:
      - ./api/.env
    environment:
      - THIS_API_SERVER_PORT=${THIS_API_SERVER_PORT}
      - RDBMS_HOST=${RDBMS_HOST}
      - RDBMS_USER=${RDBMS_USER}
      - RDBMS_PASSWORD=${RDBMS_PASSWORD}
      - RDBMS_DATABSE=${RDBMS_DATABASE}
  proxy:
    container_name: proxy
    build:
      dockerfile: Dockerfile
      context: ./docker/proxy
    ports:
      - 8080:80
    depends_on:
      - api
volumes:
  rdbms:
